export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const SORT_MOVIES = 'SORT_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
