export const testMovie = {
  id: 1,
  title: 'Test Movie',
  original_title: 'Test Movie',
  name: 'Test Movie',
  original_name: 'Test Movie',
  overview: 'Overview mocked',
  backdrop_path: 'backdrop.jpg',
  poster_path: 'poster.jpg',
  popularity: 100,
  vote_count: 100,
  vote_average: 5,
  genre_ids: [1],
  original_language: 'english',
  release_date: '2010-01-01',
  adult: false,
  video: true,
  origin_country: ['USA'],
  first_air_date: '2010-01-01',
};

export const testMovieWoPosters = {
  id: 2,
  title: 'Test Movie',
  original_title: 'Test Movie',
  name: 'Test Movie',
  original_name: 'Test Movie',
  overview: 'Overview mocked',
  backdrop_path: null,
  poster_path: null,
  popularity: 100,
  vote_count: 100,
  vote_average: 5,
  genre_ids: [1],
  original_language: 'english',
  release_date: '2010-01-01',
  adult: false,
  video: true,
  origin_country: ['USA'],
  first_air_date: '2010-01-01',
};

export const testMovieList = [
  testMovie,
  testMovieWoPosters,
];
